### ISSUE TITLE
Game Stat View 만들기

### ISSUE THREAD

**Issue by LeeJuhae** [42Sloth/game-service#16]
![image](https://user-images.githubusercontent.com/43032377/126035674-f4779ed0-93c7-4b26-8cb3-5f90a18c8629.png)

### URL : `/stats`
![image](https://user-images.githubusercontent.com/43032377/126035681-103fc5e3-c47e-4865-9e4e-684e151c65ae.png)

**Comment by nonalias** [comment]
## Count
`baseurl: /game`

### win
`@Get('/result/:username/count/win')`

### lose
`@Get('/result/:username/count/lose')`

### all
`@Get('/result/:username/count/all')`

## Stats
### all
`@Get('/result/:username/all')`
